21520613_KiemTraThucHanhDotNet/Areas/Admin/Controllers/HomeAdminController.cs
using _21520613_KiemTraThucHanhDotNet.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;

namespace _21520613_KiemTraThucHanhDotNet.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Route("admin")]
    [Route("admin/homeadmin")]
    public class HomeAdminController : Controller
    {
        QlbanVaLiContext db = new QlbanVaLiContext();
        [Route("")]
        [Route("index")]
        public IActionResult Index()
        {
            return View();

        }
        [Route("product_list")]
        public IActionResult Manage_Product()
        {
            var ps = db.TDanhMucSps.ToList();
            return View(ps);
        }
        [Route("add")]
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.MaChatLieu = new SelectList(db.TChatLieus, "MaChatLieu", "ChatLieu");
            ViewBag.MaHangSx = new SelectList(db.THangSxes, "MaHangSx", "HangSx");
            ViewBag.MaNuocSx = new SelectList(db.TQuocGia, "MaNuoc", "TenNuoc");
            ViewBag.MaLoai = new SelectList(db.TLoaiSps, "MaLoai", "Loai");
            ViewBag.MaDt = new SelectList(db.TLoaiDts, "MaDt", "TenLoai");
            return View();
        }
        [Route("add")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Add(TDanhMucSp dm)
        {
            if (ModelState.IsValid)
            {
                db.Add(dm);
                db.SaveChanges();
                return RedirectToAction("Manage_Product");
            }
            return View(dm);
        }
        [Route("edit")]
        [HttpGet]
        public IActionResult Edit(string id)
        {
            ViewBag.MaChatLieu = new SelectList(db.TChatLieus, "MaChatLieu", "ChatLieu");
            ViewBag.MaHangSx = new SelectList(db.THangSxes, "MaHangSx", "HangSx");
            ViewBag.MaNuocSx = new SelectList(db.TQuocGia, "MaNuoc", "TenNuoc");
            ViewBag.MaLoai = new SelectList(db.TLoaiSps, "MaLoai", "Loai");
            ViewBag.MaDt = new SelectList(db.TLoaiDts, "MaDt", "TenLoai");
            var updated = db.TDanhMucSps.Find(id);
            return View(updated);
        }
        [Route("edit")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(TDanhMucSp dm)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dm).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Manage_Product");
            }
            return View(dm);
        }
        [HttpGet]
        public IActionResult Delete(string id)
        {
            TempData["message"] = "Chua xoa";
            var ctSp = db.TChiTietSanPhams.Where(ct=>ct.MaSp.Equals(id)).ToList();
            var tenSp = db.TDanhMucSps.Where(ct => ct.MaSp.Equals(id)).Select(ct => ct.TenSp).FirstOrDefault();
            if (ctSp.Count > 0)
            {
                TempData["message"] = "Can't remove " + tenSp;
                return RedirectToAction("Manage_Product", "homeadmin");
            }
            var listHinhAnh = db.TAnhSps.Where(anh=>anh.MaSp.Equals(id)).ToList();
            if (listHinhAnh.Any())
            {
                db.RemoveRange(listHinhAnh);
            }
            db.Remove(db.TDanhMucSps.Find(id));
            db.SaveChanges();
            TempData["message"] = tenSp + " Successfully removed";
            return RedirectToAction("Manage_Product", "homeadmin");



        }

    }
}

21520613_KiemTraThucHanhDotNet/Areas/Admin/Views/HomeAdmin/Add.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model _21520613_KiemTraThucHanhDotNet.Models.TDanhMucSp

@{
    ViewData["Title"] = "Add";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";

}

<h1>Add</h1>

<h4>TDanhMucSp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post" asp-action="Add">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MaSp" class="control-label"></label>
                <input asp-for="MaSp" class="form-control" />
                <span asp-validation-for="MaSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TenSp" class="control-label"></label>
                <input asp-for="TenSp" class="form-control" />
                <span asp-validation-for="TenSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaChatLieu" class="control-label"></label>
                <select asp-for="MaChatLieu" class ="form-control" asp-items="ViewBag.MaChatLieu"></select>
            </div>
            <div class="form-group">
                <label asp-for="NganLapTop" class="control-label"></label>
                <input asp-for="NganLapTop" class="form-control" />
                <span asp-validation-for="NganLapTop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CanNang" class="control-label"></label>
                <input asp-for="CanNang" class="form-control" />
                <span asp-validation-for="CanNang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoNoi" class="control-label"></label>
                <input asp-for="DoNoi" class="form-control" />
                <span asp-validation-for="DoNoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaHangSx" class="control-label"></label>
                <select asp-for="MaHangSx" class ="form-control" asp-items="ViewBag.MaHangSx"></select>
            </div>
            <div class="form-group">
                <label asp-for="MaNuocSx" class="control-label"></label>
                <select asp-for="MaNuocSx" class ="form-control" asp-items="ViewBag.MaNuocSx"></select>
            </div>
            <div class="form-group">
                <label asp-for="MaDacTinh" class="control-label"></label>
                <input asp-for="MaDacTinh" class="form-control" />
                <span asp-validation-for="MaDacTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThoiGianBaoHanh" class="control-label"></label>
                <input asp-for="ThoiGianBaoHanh" class="form-control" />
                <span asp-validation-for="ThoiGianBaoHanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiThieuSp" class="control-label"></label>
                <input asp-for="GioiThieuSp" class="form-control" />
                <span asp-validation-for="GioiThieuSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChietKhau" class="control-label"></label>
                <input asp-for="ChietKhau" class="form-control" />
                <span asp-validation-for="ChietKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <select asp-for="MaLoai" class ="form-control" asp-items="ViewBag.MaLoai"></select>
            </div>
            <div class="form-group">
                <label asp-for="MaDt" class="control-label"></label>
                <select asp-for="MaDt" class ="form-control" asp-items="ViewBag.MaDt"></select>
            </div>
            <div class="form-group">
                <label asp-for="AnhDaiDien" class="control-label"></label>
                <input asp-for="AnhDaiDien" class="form-control" />
                <span asp-validation-for="AnhDaiDien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaNhoNhat" class="control-label"></label>
                <input asp-for="GiaNhoNhat" class="form-control" />
                <span asp-validation-for="GiaNhoNhat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaLonNhat" class="control-label"></label>
                <input asp-for="GiaLonNhat" class="form-control" />
                <span asp-validation-for="GiaLonNhat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

21520613_KiemTraThucHanhDotNet/Areas/Admin/Views/HomeAdmin/Edit.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model _21520613_KiemTraThucHanhDotNet.Models.TDanhMucSp

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Edit</h1>

<h4>TDanhMucSp</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="MaSp" />
            <div class="form-group">
                <label asp-for="TenSp" class="control-label"></label>
                <input asp-for="TenSp" class="form-control" />
                <span asp-validation-for="TenSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaChatLieu" class="control-label"></label>
                <select asp-for="MaChatLieu" class="form-control" asp-items="ViewBag.MaChatLieu"></select>
                <span asp-validation-for="MaChatLieu" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NganLapTop" class="control-label"></label>
                <input asp-for="NganLapTop" class="form-control" />
                <span asp-validation-for="NganLapTop" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Model" class="control-label"></label>
                <input asp-for="Model" class="form-control" />
                <span asp-validation-for="Model" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CanNang" class="control-label"></label>
                <input asp-for="CanNang" class="form-control" />
                <span asp-validation-for="CanNang" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DoNoi" class="control-label"></label>
                <input asp-for="DoNoi" class="form-control" />
                <span asp-validation-for="DoNoi" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaHangSx" class="control-label"></label>
                <select asp-for="MaHangSx" class="form-control" asp-items="ViewBag.MaHangSx"></select>
                <span asp-validation-for="MaHangSx" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaNuocSx" class="control-label"></label>
                <select asp-for="MaNuocSx" class="form-control" asp-items="ViewBag.MaNuocSx"></select>
                <span asp-validation-for="MaNuocSx" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaDacTinh" class="control-label"></label>
                <input asp-for="MaDacTinh" class="form-control" />
                <span asp-validation-for="MaDacTinh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Website" class="control-label"></label>
                <input asp-for="Website" class="form-control" />
                <span asp-validation-for="Website" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ThoiGianBaoHanh" class="control-label"></label>
                <input asp-for="ThoiGianBaoHanh" class="form-control" />
                <span asp-validation-for="ThoiGianBaoHanh" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GioiThieuSp" class="control-label"></label>
                <input asp-for="GioiThieuSp" class="form-control" />
                <span asp-validation-for="GioiThieuSp" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ChietKhau" class="control-label"></label>
                <input asp-for="ChietKhau" class="form-control" />
                <span asp-validation-for="ChietKhau" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaLoai" class="control-label"></label>
                <select asp-for="MaLoai" class="form-control" asp-items="ViewBag.MaLoai"></select>
                <span asp-validation-for="MaLoai" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MaDt" class="control-label"></label>
                <select asp-for="MaDt" class="form-control" asp-items="ViewBag.MaDt"></select>
                <span asp-validation-for="MaDt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AnhDaiDien" class="control-label"></label>
                <input asp-for="AnhDaiDien" class="form-control" />
                <span asp-validation-for="AnhDaiDien" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaNhoNhat" class="control-label"></label>
                <input asp-for="GiaNhoNhat" class="form-control" />
                <span asp-validation-for="GiaNhoNhat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GiaLonNhat" class="control-label"></label>
                <input asp-for="GiaLonNhat" class="form-control" />
                <span asp-validation-for="GiaLonNhat" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

21520613_KiemTraThucHanhDotNet/Areas/Admin/Views/HomeAdmin/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>Index</h1>

21520613_KiemTraThucHanhDotNet/Areas/Admin/Views/HomeAdmin/Manage_Product.cshtml
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@model IEnumerable<_21520613_KiemTraThucHanhDotNet.Models.TDanhMucSp>

@{
    ViewData["Title"] = "Manage_Product";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<h1>@TempData["message"]</h1>

<p> 
    <a asp-action="Add" asp-controller="HomeAdmin">Create New</a>
</p>
<table class="table">
    <thead class="table-warning">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TenSp)
            </th>
            
            <th>
                @Html.DisplayNameFor(model => model.CanNang) (kg)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DoNoi)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ThoiGianBaoHanh)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaNhoNhat)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GiaLonNhat)
            </th>
         
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            int i = 0;
            string @cls = "table-success";
        }
@foreach (var item in Model) {
            i++;
            cls = i%2==0?"table-primary":"table-success";
            
            <tr class="@cls">
            <td>
                @Html.DisplayFor(modelItem => item.TenSp)
            </td>
  
            <td>
                @Html.DisplayFor(modelItem => item.CanNang)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DoNoi)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ThoiGianBaoHanh)
            </td>
        
            <td>
                @Html.DisplayFor(modelItem => item.GiaNhoNhat)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiaLonNhat)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.MaSp">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.MaSp">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.MaSp">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>